#!/usr/bin/env php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

use App\Models\Coupon;

// Stop if we're trying to run via a non-cli interface such as a web server.
if (php_sapi_name() != "cli") {
    exit("cli only");
}

$coupons = Coupon::getHidden();

$coupons_ids = array_map(fn ($value): int => $value["id_coupon"], $coupons);

if (Coupon::unhide($coupons_ids)) {

    echo "Coupons " . implode(' ', $coupons_ids) . " are unhide \n";
} else {
    echo "Coupons " . implode(' ', $coupons_ids) . " could not be unhide \n";
}
